services:
  app:
    container_name: front-mapa
    image: front-painel-empresarial:1.0
    build:
      context: ./front
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: api-mapa
    image: api-painel-empresarial:1.0
    build:
      context: ./api
    restart: unless-stopped