services:
  frontend:
    container_name: front-painel-empresarial
    image: front-painel-empresarial:1.0
    build:
      context: ./front  # Ajustado de ./frontend para ./front
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    container_name: api-painel-empresarial
    image: api-painel-empresarial:1.0
    build:
      context: ./api    # Ajustado de ./backend para ./api
    ports:
      - "5050:8003"
    restart: unless-stopped